### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/navstevy#10]
- [x] Úvod @luboshellesch 

- [x] Všeobecný popis @TtT0m1n0 

- [x] Špecifické požiadavky @TBucsi @Metcoler

**Comment by luboshellesch** [comment]
Dokument je napísaný, skontrolovaný ešte treba doplniť Špecifické požiadavky @TBucsi @Metcoler a finalizovať úpravy

**Comment by Metcoler** [comment]
Dokument nie je vôbec skontrolovaný a špecifické požiadávky tam boli skôr ako úvod a všeobecný popis. Treba dokument skontrolovať, červenou farbou sú vyznačené veci, ktoré sme na dnešnom stretnutí ešte menili / pridávali

**Comment by Metcoler** [comment]
Treba sa zamyslieť ešte nad stránkou štatistika (je to skôr história) kde by bolo možné pravdepodobne filtrovať návštevy za nejaké časové obdobie a vyhľadávať podľa zadaného textu. Taktiež treba ešte dokument naformátovať, aby sme ho mohli poslať zadávateľovi na potvrdenie.

**Comment by Metcoler** [comment]
Katalóg požiadaviek čaká na schválenie zadávateľom

**Comment by Metcoler** [comment]
Katalóg požiadaviek je v poriadku, potvrdený zadávateľom.
