### ISSUE TITLE
Class Mainframe

### ISSUE THREAD

**Issue by TtT0m1n0** [TIS2023-FMFI/navstevy#12]
- [x] Vytvorenie Class diagramu 

link diagramu: https://app.moqups.com/vMJA6DrIvqXOTP9dbSigmHIcqtAuDyhp/view/page/a6cf6c9db

- [x]  Príprava objektov v kóde

**Comment by TtT0m1n0** [comment]
Dorobena cast diagramu pre triedy tvoriace GUI. Postupne pridavanie zakladov tried na GIT.

treba este: 

- [ ] doplnit diagram triedami tabletu 

- [ ] doplnit diagram triedou prepojenia medzi tabletom a desktopom

**Comment by TtT0m1n0** [comment]
@Metcoler @TBucsi 
Problem nepripojeneho tabletu budeme ako riesit?
Bude aplikacia bezat a bude len nejaky popup ze je nezapojeny/neaktivny?

**Comment by luboshellesch** [comment]
Pri zapisovaní do súboru treba myslieť na to aby sa zbytočne neprepisoval celý, teda len "pridávať" na koniec súboru kedy sa bude dať:
- pri zapisovaní odchodu a recenzii
- pri editovaní
Treba robiť kontrolu či je možné len pridávať resp. či prebieha len jedna návšteva.

**Comment by luboshellesch** [comment]
Vytvoriť Mediator classu, ktorá bude mať pod sebou Návštevu, Súbor a Zobrazenie! Bude v nej uložený napríklad načítaný list všetkých návštev.

**Comment by luboshellesch** [comment]
Aby sme predišli nedorozumeniam dávam vedieť že som premenoval som všetky triedy do angličtiny.
