### ISSUE TITLE
Prehlad Technologii GUI

### ISSUE THREAD

**Issue by TtT0m1n0** [TIS2023-FMFI/navstevy#14]
Skuska vytvorenia Gui pomocou frames pomocou ktorych vieme mat viacero windows prepojenych. Tuto feature vieme pouzit aj na hlavne menu aj na popups.

https://github.com/TIS2023-FMFI/navstevy/blob/main/src/temp/GUI_classes.py

**Comment by TtT0m1n0** [comment]
@luboshellesch Nasiel som sposob akym by sme mohli robit krajsie a prehladnejsie GUI: https://github.com/TIS2023-FMFI/navstevy/blob/main/src/temp/GUI_Custom_Classes.py tu je skuska ako to vyzera na kode co sme robili ako testovaci. V podstate to je len rozsireny tkinter o par veci. Chceli by sme pokracovat dalej v tom?

**Comment by luboshellesch** [comment]
Vyzerá to super, môžeme to využiť.
