### ISSUE TITLE
Desktop GUI - Visitor

### ISSUE THREAD

**Issue by TtT0m1n0** [TIS2023-FMFI/navstevy#23]
@luboshellesch @TtT0m1n0 
Vytvorenie a pripravenie triedy Visitor ore jednoduche spravovanie a pracovanie s datami navstev.

**Comment by luboshellesch** [comment]
Vytvorenie vnútorného unikátneho ID pre každú návštevu. Možnosti:
- jednoduché pridávanie ID ako čísla podľa počtu zápisov v súbore (ten sa môže zisť pri načítaní návštev a ďalej sa bude správne zvyšovať)
- vytvorenie niekoľko-ciferného (rovnaký počet cifier pre každého) unikátneho čísla podľa údajov ako priezvisko a čas príchodu
- iné riešenia..
