### ISSUE TITLE
Desktop GUI - Prepojenie Mediatora a GUI

### ISSUE THREAD

**Issue by luboshellesch** [TIS2023-FMFI/navstevy#31]
@luboshellesch @TtT0m1n0 
GUI poterbuje:

- [x]  pridanie návštevníka

- [x]  zoznam prebiahajúcich návštev
- [x] zoznam všetkých návštev (+ podľa filtru)
- [x]  potvrdenie návšetvy
- [x]  potvrdenie odchodu a recenzie
- [x]  editovanie návštevy

Pozor na ukladanie po editovaní a potvrdení návštevy!

**Comment by luboshellesch** [comment]
Pridanie návšetvníka:
mediator dostane: meno - string, priezvisko - string, ID (karty) - int, SPZ - string, Meno firmy - string, Počet ludí - int, 
Dôvod návštevy - zatiaľ string, treba sa dohodnúť či potrebujú mať možnosť upravovať dôvody z rollupu

**Comment by Metcoler** [comment]
Nedokončené detaily presunuté do nových issues
