### ISSUE TITLE
Plán implementácie

### ISSUE THREAD

**Issue by TBucsi** [TIS2023-FMFI/navstevy#38]
Je potrebné vytvoriť plán implementácie, podľa ktorého budeme postupovať pri následnej implementácie

**Comment by luboshellesch** [comment]
@TBucsi potrebujem aby si mi poslal plán implementácie tabletovej aplikácie

**Comment by TBucsi** [comment]
Plán implementácie tabletovej aplikácií som zavesil na google drive
