### ISSUE TITLE
Spustenie aplikacie v user space

### ISSUE THREAD

**Issue by TBucsi** [TIS2023-FMFI/navstevy#5]
Možnosť že aplikácia a dáta bežia z usb

**Comment by pavelpetrovic** [comment]
pozrite si pripadne https://github.com/TIS2020-FMFI/plazma

**Comment by Metcoler** [comment]
Obyčajná .exe aplikácia by mala normálne bežať v user space. Vyskúšame poslať zadávateľovi python tkinter aplikáciu exportovanú do .exe , ktorú skúsi spustiť na počítači, kde má bežať finálna aplikácia.
