### ISSUE TITLE
Zapojenie komunikácie do PC aplikácie

### ISSUE THREAD

**Issue by Metcoler** [TIS2023-FMFI/navstevy#51]
Treba zapojiť classu komunikácie do PC aplikácie.

**Comment by luboshellesch** [comment]
Do mediátora som pridal metódu na komunikáciu s tabletom. Využívajúcu triedu Communication.

**Comment by luboshellesch** [comment]
Už som tam pridal aj metódu na komunikáciu pri review. V GUI som spravil aj potrebné veci aby sa spustila prezentácia. Okrem toho čo sa má spraviť keď to prebehne úspešne alebo neúspešne. A na review je spravená funkcia v mediátorovi ale ešte ju treba pridať do GUI.

**Comment by Metcoler** [comment]
Počítačová aplikácia funguje ako tak dobre, treba doladiť stále detaily
