### ISSUE TITLE
Dokumentacia 2 stretnutia

### ISSUE THREAD

**Issue by TtT0m1n0** [TIS2023-FMFI/navstevy#6]
https://github.com/TIS2023-FMFI/navstevy/blob/main/docs/stretnutie_17_10.txt

treba skontrolovat s nahravkou a poslat mail s dodatocnymi otazkami

**Comment by luboshellesch** [comment]
Updatol som dokument o vynechané údaje z nahrávky.

**Comment by TBucsi** [comment]
Skontroloval som dokument.
