### ISSUE TITLE
Ukladanie dát (text + obrázok)

### ISSUE THREAD

**Issue by Metcoler** [TIS2023-FMFI/navstevy#7]
V tomto issue chceme vyriešiť problém ako ukladáť potrebné dáta automaticky pomocou zatiaľ ľubovoľného programovacieho jazyka, tak aby na ploche bol jeden súbor (asi .csv) kde budú v riadkoch údaje o návšteve priamo aj s podpisom. Musíme teda vyriešiť ako kombinovať textové dáta s obrázkom.

**Comment by luboshellesch** [comment]
Po krátkom hľadaní som našiel napríklad https://stackoverflow.com/a/2333581 , kde je to pekne napísané. Ale pokiaľ sa teda nechceme v našej aplikácii zaoberať aj konvertovaním do textu zapísaných obrázkov a naopak, tak by sme mali ukladať podpisy nejako inak. Najjednoduchšie asi do nejakého súboru.

**Comment by TBucsi** [comment]
Ak by sme sa rozhodli písať projekt v python, tak ak chceme mohli by sme všetko písať do doc/docx file, našiel som knižnicu, ktorá by mohla byť na to vhodná https://python-docx.readthedocs.io/en/latest/, vyskúšal som ju, vyzerá byť funkčná a jednoduchá na použitie.

**Comment by Metcoler** [comment]
Ako sme sa dohodli, dáta budeme ukladať do .txt súboru, kde budú informácie o návštevách (meno, priezvisko, datum, dovod, ...). Podpis bude uložený ako obrázok v priečinku a do .txt súboru pridáme informáciu, ktorý podpis patrí danej návšteve.
