### ISSUE TITLE
GUI Aplikacii

### ISSUE THREAD

**Issue by TtT0m1n0** [TIS2023-FMFI/navstevy#9]
Znazornenie rozhrania pre desktop aplikaciu pomocou moqups: https://app.moqups.com/vMJA6DrIvqXOTP9dbSigmHIcqtAuDyhp/view/page/a8128c6c1

**Comment by TtT0m1n0** [comment]
GUI Desktopu aj tabletu je pripraveny na odkontrolovanie

**Comment by Metcoler** [comment]
Zadávateľ potvrdil GUI aplikácie, všetko je v poriadku. Mali by sme si však splniť povinnosti a ešte dohodnúť jedno stretnutie, kde si celé GUI prejdeme aj so zadávateľom.
